"""add printer attachments

Revision ID: 128977e3551e
Revises: 54db9bbbf52c
Create Date: 2026-07-11 12:36:07.843277

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '128977e3551e'
down_revision: Union[str, None] = '54db9bbbf52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_attachments_id'), 'printer_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_printer_attachments_printer_id'), 'printer_attachments', ['printer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printer_attachments_printer_id'), table_name='printer_attachments')
    op.drop_index(op.f('ix_printer_attachments_id'), table_name='printer_attachments')
    op.drop_table('printer_attachments')
    # ### end Alembic commands ###
