"""add inventory tables

Revision ID: 15a0ef627a4f
Revises: ecabc5be4af0
Create Date: 2026-07-11 09:14:25.586968

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '15a0ef627a4f'
down_revision: Union[str, None] = 'ecabc5be4af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('ram', 'ssd', 'nvme', 'hdd', 'access_point', 'network_switch', 'power_supply', 'server_parts', 'misc', name='inventorycategory'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('shelf_life_months', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=False)
    op.create_table('inventory_deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=False),
    sa.Column('deployed_by_id', sa.Integer(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['it_assets.id'], ),
    sa.ForeignKeyConstraint(['deployed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_deployments_asset_id'), 'inventory_deployments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_inventory_deployments_id'), 'inventory_deployments', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_deployments_item_id'), 'inventory_deployments', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hd_tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'in_progress', 'pending', 'resolved', 'closed', name='hd_ticket_status'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'critical', name='hd_ticket_priority'), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sla_due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['it_assets.id'], name=op.f('hd_tickets_asset_id_fkey')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('hd_tickets_assigned_to_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('hd_tickets_created_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hd_tickets_pkey'))
    )
    op.create_index(op.f('ix_hd_tickets_status'), 'hd_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_hd_tickets_priority'), 'hd_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_hd_tickets_id'), 'hd_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_hd_tickets_created_by_id'), 'hd_tickets', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_hd_tickets_created_at'), 'hd_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_hd_tickets_category'), 'hd_tickets', ['category'], unique=False)
    op.create_index(op.f('ix_hd_tickets_assigned_to_id'), 'hd_tickets', ['assigned_to_id'], unique=False)
    op.create_table('alembic_version_helpdesk',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_helpdesk_pkc'))
    )
    op.create_table('hd_ticket_updates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_internal', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('hd_ticket_updates_author_id_fkey')),
    sa.ForeignKeyConstraint(['ticket_id'], ['hd_tickets.id'], name=op.f('hd_ticket_updates_ticket_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hd_ticket_updates_pkey'))
    )
    op.create_index(op.f('ix_hd_ticket_updates_ticket_id'), 'hd_ticket_updates', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_hd_ticket_updates_id'), 'hd_ticket_updates', ['id'], unique=False)
    op.drop_index(op.f('ix_inventory_deployments_item_id'), table_name='inventory_deployments')
    op.drop_index(op.f('ix_inventory_deployments_id'), table_name='inventory_deployments')
    op.drop_index(op.f('ix_inventory_deployments_asset_id'), table_name='inventory_deployments')
    op.drop_table('inventory_deployments')
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
