"""add asset photo fields

Revision ID: 32fb793d8244
Revises: 128977e3551e
Create Date: 2026-07-11 13:55:40.889977

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '32fb793d8244'
down_revision: Union[str, None] = '128977e3551e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('it_assets', sa.Column('photo_filename', sa.String(), nullable=True))
    op.add_column('it_assets', sa.Column('photo_is_model_photo', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('it_assets', 'photo_is_model_photo')
    op.drop_column('it_assets', 'photo_filename')
    # ### end Alembic commands ###
