"""change printer costs to string

Revision ID: 42dfe9807412
Revises: 32fb793d8244
Create Date: 2026-07-12 03:57:25.842794

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '42dfe9807412'
down_revision: Union[str, None] = '32fb793d8244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('printer_repairs', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('printers', 'purchase_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('printers', 'purchase_price',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('printer_repairs', 'cost',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
