"""add is_retired to deployments

Revision ID: 54db9bbbf52c
Revises: e7ddc018de17
Create Date: 2026-07-11 10:53:04.005222

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '54db9bbbf52c'
down_revision: Union[str, None] = 'e7ddc018de17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_deployments', sa.Column('is_retired', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('inventory_deployments', sa.Column('retired_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_deployments', 'retired_at')
    op.drop_column('inventory_deployments', 'is_retired')
    # ### end Alembic commands ###
