"""init

Revision ID: cf96b241efbe
Revises: 
Create Date: 2026-07-02 15:41:56.880659

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cf96b241efbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
