"""add stock receipts, opening stock

Revision ID: e7ddc018de17
Revises: 15a0ef627a4f
Create Date: 2026-07-11 10:42:44.482965

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e7ddc018de17'
down_revision: Union[str, None] = '15a0ef627a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_receipts_id'), 'stock_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_stock_receipts_item_id'), 'stock_receipts', ['item_id'], unique=False)
    op.add_column('inventory_items', sa.Column('opening_stock', sa.Integer(), nullable=False, server_default='0'))
    op.execute('UPDATE inventory_items SET opening_stock = COALESCE(quantity, 0)')
    op.drop_column('inventory_items', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('inventory_items', 'opening_stock')
    op.drop_index(op.f('ix_stock_receipts_item_id'), table_name='stock_receipts')
    op.drop_index(op.f('ix_stock_receipts_id'), table_name='stock_receipts')
    op.drop_table('stock_receipts')
    # ### end Alembic commands ###
