"""add printers table

Revision ID: ecabc5be4af0
Revises: f670b392b67a
Create Date: 2026-07-05 16:12:23.736657

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ecabc5be4af0'
down_revision: Union[str, None] = 'f670b392b67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('asset_tag', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'offline', 'maintenance', 'retired', name='printerstatus'), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printers_asset_tag'), 'printers', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_printers_contract_id'), 'printers', ['contract_id'], unique=False)
    op.create_index(op.f('ix_printers_id'), 'printers', ['id'], unique=False)
    op.create_table('printer_repairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('repair_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('document_ref', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_repairs_id'), 'printer_repairs', ['id'], unique=False)
    op.create_index(op.f('ix_printer_repairs_printer_id'), 'printer_repairs', ['printer_id'], unique=False)
    op.drop_table('alembic_version_helpdesk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version_helpdesk',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_helpdesk_pkc'))
    )
    op.drop_index(op.f('ix_printer_repairs_printer_id'), table_name='printer_repairs')
    op.drop_index(op.f('ix_printer_repairs_id'), table_name='printer_repairs')
    op.drop_table('printer_repairs')
    op.drop_index(op.f('ix_printers_id'), table_name='printers')
    op.drop_index(op.f('ix_printers_contract_id'), table_name='printers')
    op.drop_index(op.f('ix_printers_asset_tag'), table_name='printers')
    op.drop_table('printers')
    # ### end Alembic commands ###
