"""add contracts v2

Revision ID: f670b392b67a
Revises: cf96b241efbe
Create Date: 2026-07-03 17:06:38.827024

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f670b392b67a'
down_revision: Union[str, None] = 'cf96b241efbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contract_type', sa.Enum('saas', 'support', 'vendor', name='contracttype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'expiring_soon', 'expired', 'cancelled', name='contractstatus'), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('vendor_contact_name', sa.String(), nullable=True),
    sa.Column('vendor_contact_email', sa.String(), nullable=True),
    sa.Column('vendor_contact_phone', sa.String(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('billing_cycle', sa.Enum('monthly', 'quarterly', 'annual', 'one_time', name='billingcycle'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_name'), 'contracts', ['name'], unique=False)
    op.create_index(op.f('ix_contracts_owner_id'), 'contracts', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_hd_ticket_updates_id'), table_name='hd_ticket_updates')
    op.drop_index(op.f('ix_hd_ticket_updates_ticket_id'), table_name='hd_ticket_updates')
    op.drop_table('hd_ticket_updates')
    op.drop_table('alembic_version_helpdesk')
    op.drop_index(op.f('ix_hd_tickets_assigned_to_id'), table_name='hd_tickets')
    op.drop_index(op.f('ix_hd_tickets_category'), table_name='hd_tickets')
    op.drop_index(op.f('ix_hd_tickets_created_at'), table_name='hd_tickets')
    op.drop_index(op.f('ix_hd_tickets_created_by_id'), table_name='hd_tickets')
    op.drop_index(op.f('ix_hd_tickets_id'), table_name='hd_tickets')
    op.drop_index(op.f('ix_hd_tickets_priority'), table_name='hd_tickets')
    op.drop_index(op.f('ix_hd_tickets_status'), table_name='hd_tickets')
    op.drop_table('hd_tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hd_tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'in_progress', 'pending', 'resolved', 'closed', name='hd_ticket_status'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'critical', name='hd_ticket_priority'), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sla_due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['it_assets.id'], name=op.f('hd_tickets_asset_id_fkey')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('hd_tickets_assigned_to_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('hd_tickets_created_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hd_tickets_pkey'))
    )
    op.create_index(op.f('ix_hd_tickets_status'), 'hd_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_hd_tickets_priority'), 'hd_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_hd_tickets_id'), 'hd_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_hd_tickets_created_by_id'), 'hd_tickets', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_hd_tickets_created_at'), 'hd_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_hd_tickets_category'), 'hd_tickets', ['category'], unique=False)
    op.create_index(op.f('ix_hd_tickets_assigned_to_id'), 'hd_tickets', ['assigned_to_id'], unique=False)
    op.create_table('alembic_version_helpdesk',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_helpdesk_pkc'))
    )
    op.create_table('hd_ticket_updates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_internal', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('hd_ticket_updates_author_id_fkey')),
    sa.ForeignKeyConstraint(['ticket_id'], ['hd_tickets.id'], name=op.f('hd_ticket_updates_ticket_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hd_ticket_updates_pkey'))
    )
    op.create_index(op.f('ix_hd_ticket_updates_ticket_id'), 'hd_ticket_updates', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_hd_ticket_updates_id'), 'hd_ticket_updates', ['id'], unique=False)
    op.drop_index(op.f('ix_contracts_owner_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_name'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
