{
 "title": "Vdlarr - PromEx Application Dashboard",
 "description": "All the data that is presented here is captured by the PromEx Application plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/application.ex)",
 "tags": [
  "PromEx",
  "Application",
  "vdlarr"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Prometheus Job",
    "query": "label_values(vdlarr_prom_ex_prom_ex_status_info, job)"
   },
   {
    "name": "instance",
    "label": "Application Instance",
    "query": "label_values(vdlarr_prom_ex_prom_ex_status_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Application Uptime",
   "type": "stat",
   "description": "The amount of time that the application has been running.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vdlarr_prom_ex_application_uptime_milliseconds_count{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Dependency Information",
   "type": "table",
   "description": "The data is populated by the PromEx Application plugin and provides information regarding your application's dependencies.",
   "gridPos": { "h": 36, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "vdlarr_prom_ex_application_dependency_info{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Application Name",
   "type": "stat",
   "description": "The name of the primary application that is running.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vdlarr_prom_ex_application_primary_info{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Application Git SHA",
   "type": "stat",
   "description": "The Git SHA of the application.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vdlarr_prom_ex_application_git_sha_info{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Application Git Author",
   "type": "stat",
   "description": "The author of the application's last Git commit.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vdlarr_prom_ex_application_git_author_info{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Application Version",
   "type": "stat",
   "description": "The version of the primary application that is running.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vdlarr_prom_ex_application_primary_info{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Application Modules Loaded",
   "type": "stat",
   "description": "The number of modules loaded by the primary application that is running.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vdlarr_prom_ex_application_primary_info{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  }
 ]
}