"""Alembic environment — scoped to core_ tables only.

Shared-DB discipline (v1 lesson): this app only ever autogenerates
against its own table prefix, with its own version table
(alembic_version_core). Helpdesk v2 / CRM v2 will bring their own
prefixes + version tables when they join this database.

Also (v1 lesson): review every autogenerated migration and strip any
drop statements for tables that are not core_-prefixed.
"""

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.db import Base
from app.core import models  # noqa: F401  (register models on Base.metadata)

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

PREFIX = "core_"


def get_url() -> str:
    url = os.environ.get(
        "DATABASE_URL", "postgresql+asyncpg://itops2:itops2@db:5432/itops2"
    )
    # alembic runs sync
    return url.replace("+asyncpg", "+psycopg2")


def include_object(object, name, type_, reflected, compare_to):
    if type_ == "table":
        return name.startswith(PREFIX)
    return True


def run_migrations_offline() -> None:
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        include_object=include_object,
        version_table="alembic_version_core",
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    cfg = config.get_section(config.config_ini_section, {})
    cfg["sqlalchemy.url"] = get_url()
    connectable = engine_from_config(cfg, prefix="sqlalchemy.", poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            version_table="alembic_version_core",
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
