import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :coffer, CofferWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# No force_ssl here: this test/staging deployment (spec §11) is plain HTTP
# with no reverse-proxy TLS termination in front of it yet. Add it back
# (with rewrite_on: [:x_forwarded_proto]) once a TLS-terminating proxy is
# in place for the hardened prod compose file.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
